/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Structure of a Dungeon World monster generator questionnaire responses
 */
export interface DungeonWorldMonsterGeneratorQuestionnaire {
    name?: string;
    group?: string;
    size?: string;
    atkname?: string;
    knownfor?: string[];
    qualities?: string;
    instinct?: string;
    moves?: string;
    protection?: string;
    armaments?: string[];
    description?: string;
}
